# Generated by Django 4.2 on 2024-08-23 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_record_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата записи'),
            preserve_default=False,
        ),
    ]
