# Generated by Django 4.2 on 2024-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Отмена записи'),
            preserve_default=False,
        ),
    ]
