# Generated by Django 4.2 on 2024-08-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_record_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отмена записи'),
        ),
    ]
